command: ["streamlit", "run", "app.py", "--server.headless=true"]
env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: BL_RBAC_MODE
    value: "strict"
  - name: BL_IMAGE_BACKEND
    value: "volume"
  - name: BL_PG_SCHEMA
    value: "bl_demat"
  - name: BL_TIMEZONE
    value: "Europe/Paris"
  - name: BL_PAGE_SIZE
    value: "50"
